apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secrets
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  RABBITMQ_USER: {{ .Values.secrets.RABBITMQ_USER | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.RABBITMQ_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
