apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce.fullname" . }}-sa
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ include "ecommerce.fullname" . }}-registry-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-registry-secret
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.imagePullSecret }}
