spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///auth_test_db
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  data:
    redis:
      host: localhost
      port: 6379

app:
  security:
    jwt:
      secret: testSecretKeyThatIsAtLeast32BytesLongForHS256
      expiration-ms: 900000
      refresh-expiration-ms: 604800000

logging:
  level:
    root: ERROR
