{{- if .Values.infrastructure.postgres.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-{{ .Release.Name }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: {{ .Values.infrastructure.postgres.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.infrastructure.storageClass }}
  hostPath:
    path: /mnt/data/ecommerce/postgres-{{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.infrastructure.postgres.storage }}
  storageClassName: {{ .Values.infrastructure.storageClass }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: postgres
  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "ecommerce_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "ecommerce_user", "-d", "ecommerce_db"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
{{- end }}
