{{- if .Values.infrastructure.redis.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-{{ .Release.Name }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: {{ .Values.infrastructure.redis.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.infrastructure.storageClass }}
  hostPath:
    path: /mnt/data/ecommerce/redis-{{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.infrastructure.redis.storage }}
  storageClassName: {{ .Values.infrastructure.storageClass }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: redis
  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- end }}
