apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  DB_USER: "ecommerce_user"
  DB_PASSWORD: "ecommerce_password"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  JWT_SECRET: "vErYsEcReTkEyThAtIsAtLeAsT32ByTeSlOnGfOrHs256"
