spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payment_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    com.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
