name: Security & Quality Gates

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ "main" ]

jobs:
  trivy-fs-scan:
    name: Filesystem Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-fs-results.sarif'
          category: filesystem-scan

  trivy-config-scan:
    name: Infrastructure as Code (IaC) Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner on Helm configurations
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'helm/ecommerce'
          format: 'sarif'
          output: 'trivy-config-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Fail pipeline on critical misconfigurations

      - name: Upload Trivy IaC scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-config-results.sarif'
          category: iac-scan
